name: GitHub Actions Demo
run-name: ${{ github.actor }} is UPDATING 🚀
on:
  schedule:
    - cron: "30 4 * * 0"
jobs:
  Create-Branch:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Get current Date
        run: echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Create Branch with current Date
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: '${{ env.RELEASE_DATE }}_automation'
          sha: '${{ github.event.pull_request.head.sha }}'
      - name: Checkout new Branch in seperate folder
        uses: actions/checkout@v3
        with:
          ref: '${{ env.RELEASE_DATE }}_automation'
          path: './${{ env.RELEASE_DATE }}_automation/'
      - name: testing
        run: touch ./${{ env.RELEASE_DATE }}_automation/test123456
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: kevin.sandermann@gmail.com
          message: 'Release ${{ env.RELEASE_DATE }}_automation'
          cwd: './${{ env.RELEASE_DATE }}_automation/'


