name: Update Versions
run-name: ${{ github.actor }} is UPDATING 🚀
on: workflow_dispatch
#   schedule:
#     #UTC - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
#     - cron: '20 3 * * WED'
#     - cron: '20 3 * * SUN'
#     - cron: '15/15 * * * SUN'

jobs:
  Create-Branch:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Get current date
        run: echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: fetch
        run: git fetch origin
      - name: checkout
        run: git checkout master
      - name: pull origin
        run: git pull origin master
      - name: status
        run: git status
      - name: create branch
        run: get checkout -b ${{ env.RELEASE_DATE }}_automation
      - name: commit
        run: git commit -a -m "test"
      - name: push branch
        run: git push
