name: Update Versions
run-name: ${{ github.actor }} is UPDATING 🚀
on: workflow_dispatch
#   schedule:
#     #UTC - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
#     - cron: '20 3 * * WED'
#     - cron: '20 3 * * SUN'
#     - cron: '15/15 * * * SUN'

jobs:
  Create-Branch:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Get current date
        run: echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: fetch
        run: git fetch origin
      - name: checkout
        run: git checkout master
      - name: delete all local branches
        run: git checkout -b "tmp" || true  && git checkout master && git for-each-ref --format '%(refname:short)' refs/heads | grep -v "master\|main" | xargs git branch -D
      - name: pull origin
        run: git pull origin master
      - name: status
        run: git status
      - name: create branch
        run: git checkout -b ${{ env.RELEASE_DATE }}_automation
#       - name: update versions
#         run: bash update_versions.sh
      - name: commit
        run: git commit -a -m "test"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.RELEASE_DATE }}_automation
      - name: create PR
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/ksandermann/cloud-toolbox/pulls \
            -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"${{ env.RELEASE_DATE }}_automation","base":"master"}'
